routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

    Route::get('/', 'AdminController@dashboard')->name('index');
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('/heatmap', 'AdminController@heatmap')->name('heatmap');
    Route::get('/translation', 'AdminController@translation')->name('translation');


    Route::group(['as' => 'dispatcher.', 'prefix' => 'dispatcher'], function () {
        Route::get('/', 'DispatcherController@index')->name('index');
        Route::post('/', 'DispatcherController@store')->name('store');
        Route::get('/trips', 'DispatcherController@trips')->name('trips');
        Route::get('/trips/{trip}/{provider}', 'DispatcherController@assign')->name('assign');
        Route::get('/users', 'DispatcherController@users')->name('users');
        Route::get('/providers', 'DispatcherController@providers')->name('providers');

    });


    Route::resource('user', 'Resource\UserResource');
    Route::resource('dispatch-manager', 'Resource\DispatcherResource');
    Route::resource('account-manager', 'Resource\AccountResource');
    Route::resource('fleet', 'Resource\FleetResource');
    Route::resource('provider', 'Resource\ProviderResource');
    Route::resource('document', 'Resource\DocumentResource');
    Route::resource('promocode', 'Resource\PromocodeResource');


    Route::group(['as' => 'provider.'], function () {
        Route::get('review/provider', 'AdminController@provider_review')->name('review');
        Route::get('provider/{id}/approve', 'Resource\ProviderResource@approve')->name('approve');
        Route::get('provider/{id}/disapprove', 'Resource\ProviderResource@disapprove')->name('disapprove');
        Route::get('provider/{id}/request', 'Resource\ProviderResource@request')->name('request');
        Route::get('provider/{id}/statement', 'Resource\ProviderResource@statement')->name('statement');
        Route::resource('provider/{provider}/ProviderResource', 'Resource\ProviderDocumentResource');
        Route::delete('provider/{provider}/service/{document}', 'Resource\ProviderDocumentResource@service_destroy')->name('document.service');

    });

    Route::get('review/user', 'AdminController@user_review')->name('user.review');
    Route::get('user/{id}/request', 'Resource\UserResource@request')->name('user.request');
    Route::post('user/wallet', 'Resource\UserResource@wallet_update')->name('user.wallet');

    Route::get('map', 'AdminController@map_index')->name('map.index');
    Route::get('/map/ajax', 'AdminController@map_ajax')->name('map.ajax');

    Route::get('settings', 'AdminController@settings')->name('settings');
    Route::get('condition_settings', 'AdminController@condition_settings')->name('condition_settings');
    Route::post('condition_settings/store', 'AdminController@condition_settings_store')->name('condition_settings.store');
    Route::post('condition/destroy', 'AdminController@condition_destroy')->name('condition.destroy');

    Route::get('dash_settings', 'AdminController@dash_settings')->name('dash_settings');
    Route::post('settings/store', 'AdminController@settings_store')->name('settings.store');
    Route::post('dash_settings/store', 'AdminController@dash_settings_store')->name('dash_settings.store');
    Route::post('box_settings/store', 'AdminController@box_settings_store')->name('box_settings.store');
    Route::post('box_delete/store', 'AdminController@box_delete')->name('box_delete.delete');
    Route::get('settings/payment', 'AdminController@settings_payment')->name('settings.payment');
    Route::post('settings/payment', 'AdminController@settings_payment_store')->name('settings.payment.store');

    Route::get('profile', 'AdminController@profile')->name('profile');
    Route::post('profile', 'AdminController@profile_update')->name('profile.update');

    Route::get('password', 'AdminController@password')->name('password');
    Route::post('password', 'AdminController@password_update')->name('password.update');

    Route::get('payment', 'AdminController@payment')->name('payment');

// statements

    Route::get('/statement', 'AdminController@statement')->name('ride.statement');
    Route::get('/statement/provider', 'AdminController@statement_provider')->name('ride.statement.provider');
    Route::get('/statement/today', 'AdminController@statement_today')->name('ride.statement.today');
    Route::get('/statement/monthly', 'AdminController@statement_monthly')->name('ride.statement.monthly');
    Route::get('/statement/yearly', 'AdminController@statement_yearly')->name('ride.statement.yearly');


// Static Pages - Post updates to pages.update when adding new static pages.

    Route::get('/help', 'AdminController@help')->name('help');
    Route::get('/privacy', 'AdminController@privacy')->name('privacy');
    Route::post('/pages', 'AdminController@pages')->name('pages.update');

    Route::resource('requests', 'Resource\TripResource');
    Route::get('search/requests', 'Resource\TripResource@Searching_Request')->name('requests.search');;
    Route::get('scheduled', 'Resource\TripResource@scheduled')->name('requests.scheduled');

    Route::get('push', 'AdminController@push_index')->name('push.index');
    Route::post('push', 'AdminController@push_store')->name('push.store');


// car class and car model //

    Route::post('/condition/ChangeStatus', 'AdminController@condition_ChangeStatus')->name('condition.Change_Status');
    Route::post('Change_Status', 'AdminController@Change_Status')->name('Change_Status');


    Route::resource('transtype', 'Resource\TransportationTypeResource', ['except' => ['update', 'edit']]);
    Route::get('transtypes', 'Resource\TransportationTypeResource@transtypes')->name('transtypes');


    Route::resource('service', 'Resource\ServiceResource');
    Route::get('services', 'Resource\ServiceResource@services')->name('services');


    Route::resource('carclass', 'Resource\CarClassResource');
    Route::get('carclasses', 'Resource\CarClassResource@CarClasses')->name('carclasses');

    Route::resource('carmodel', 'Resource\CarModelResource');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| User Authentication Routes
|--------------------------------------------------------------------------
*/

Auth::routes();
    /*
    |--------------------------------------------------------------------------
    | Provider Authentication Routes
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'provider'], function () {
        Route::get('auth/facebook', 'Auth\SocialLoginController@providerToFaceBook');
        Route::get('auth/google', 'Auth\SocialLoginController@providerToGoogle');

        Route::get('/login', 'ProviderAuth\LoginController@showLoginForm');
        Route::post('/login', 'ProviderAuth\LoginController@login');
        Route::post('/logout', 'ProviderAuth\LoginController@logout');

        Route::get('/register', 'ProviderAuth\RegisterController@showRegistrationForm');
        Route::post('/register', 'ProviderAuth\RegisterController@register');

        Route::post('/password/email', 'ProviderAuth\ForgotPasswordController@sendResetLinkEmail');
        Route::post('/password/reset', 'ProviderAuth\ResetPasswordController@reset');
        Route::get('/password/reset', 'ProviderAuth\ForgotPasswordController@showLinkRequestForm');
        Route::get('/password/reset/{token}', 'ProviderAuth\ResetPasswordController@showResetForm');

    });
    /*
    |--------------------------------------------------------------------------
    | Admin Authentication Routes
    |--------------------------------------------------------------------------
    */
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
        Route::post('/login', 'AdminAuth\LoginController@login');
        Route::post('/logout', 'AdminAuth\LoginController@logout');
        Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
        Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
        Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
        Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
    });
/*
    |--------------------------------------------------------------------------
    | User Routes
    |--------------------------------------------------------------------------
    */


    Route::get('/dashboard', 'HomeController@index');
    Route::get('/services/{id}', 'Resource\ServiceResource@frontend')->name('frontend.service');
    Route::get('/about',function(){
         return view('about');
    });
    // user profiles
    Route::get('/profile', 'HomeController@profile');
    Route::get('/edit/profile', 'HomeController@edit_profile');
    Route::post('/profile', 'HomeController@update_profile');
    // update password
    Route::get('/change/password', 'HomeController@change_password');
    Route::post('/change/password', 'HomeController@update_password');
    // ride
    Route::get('/confirm/ride', 'RideController@confirm_ride');
    Route::post('/create/ride', 'RideController@create_ride');
    Route::post('/cancel/ride', 'RideController@cancel_ride');
    Route::get('/onride', 'RideController@onride');
    Route::post('/payment', 'PaymentController@payment');
    Route::post('/rate', 'RideController@rate');
    // status check
    Route::get('/status', 'RideController@status');
    // trips
    Route::get('/trips', 'HomeController@trips');
    Route::get('/upcoming/trips', 'HomeController@upcoming_trips');
    // wallet
    Route::get('/wallet', 'HomeController@wallet');
    Route::post('/add/money', 'PaymentController@add_money');
    // payment
    Route::get('/payment', 'HomeController@payment');
    // card
    Route::resource('card', 'Resource\CardResource');
    // promotions
    Route::get('/promotions', 'HomeController@promotions_index')->name('promocodes.index');
    Route::post('/promotions', 'HomeController@promotions_store')->name('promocodes.store');


    Route::get('auth/facebook', 'Auth\SocialLoginController@redirectToFaceBook');
    Route::get('auth/facebook/callback', 'Auth\SocialLoginController@handleFacebookCallback');
    Route::get('auth/google', 'Auth\SocialLoginController@redirectToGoogle');
    Route::get('auth/google/callback', 'Auth\SocialLoginController@handleGoogleCallback');
    Route::post('account/kit', 'Auth\SocialLoginController@account_kit')->name('account.kit');

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    */

    Route::get('/privacy', function () {
        $page = 'page_privacy';
        $title = 'سياسة الخصوصية';
        return view('static', compact('page', 'title'));
    });

    Route::get('/condition', function () {
        $page = 'privacy';
        $title = ' شروط الخدمة';
        return view('static2', compact('page', 'title'));
    });






    Route::get('/{lang}',function ($lang){
        if(in_array($lang,['ar','en'])){
            if (auth()->user()){
                $user=auth()->user();
                $user->lang=$lang;
                $user->save();
            }
            else{
                if(session()->has('lang')){
                    session()->forget('lang');
                }
                session()->put('lang',$lang);
            }
        }

        else{
            if (auth()->user()){
                $user=auth()->user();
                $user->lang='ar';
                $user->save();
            }
            else{
                if(session()->has('lang')){
                    session()->forget('lang');
                }
                session()->put('lang','ar');
            }
        }
        return back();
    });
    Route::group(['Middlware' => 'setlanguage'] ,  function  () {
    Route::get('/', function () {
        return view('index');
    });

}); //End Middlware

app/Http/Controllers/ProviderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\UserRequests;
use App\RequestFilter;
use App\Provider;
use Carbon\Carbon;
use App\Http\Controllers\ProviderResources\TripController;

class ProviderController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Request $request)
    {
        $this->middleware('provider');

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */

    public function incoming(Request $request)
    {
        return (new TripController())->index($request);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */

    public function accept(Request $request, $id)
    {
        return (new TripController())->accept($request, $id);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */

    public function reject($id)
    {
        return (new TripController())->destroy($id);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id)
    {
        return (new TripController())->update($request, $id);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */

    public function rating(Request $request, $id)
    {
        return (new TripController())->rate($request, $id);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function earnings()
    {
        $provider = Provider::where('id',\Auth::guard('provider')->user()->id)
                    ->with('service','accepted','cancelled')
                    ->get();

        $weekly = UserRequests::where('provider_id',\Auth::guard('provider')->user()->id)
                    ->with('payment')
                    ->where('created_at', '>=', Carbon::now()->subWeekdays(7))
                    ->get();

        $today = UserRequests::where('provider_id',\Auth::guard('provider')->user()->id)
                    ->where('created_at', '>=', Carbon::today())
                    ->count();

        $fully = UserRequests::where('provider_id',\Auth::guard('provider')->user()->id)
                    ->with('payment','service_type')
                    ->get();

        return view('provider.payment.earnings',compact('provider','weekly','fully','today'));
    }

    /**
     * available.
     *
     * @return \Illuminate\Http\Response
     */
    public function available(Request $request)
    {
        (new ProviderResources\ProfileController)->available($request);
        return back();
    }

    /**
     * Show the application change password.
     *
     * @return \Illuminate\Http\Response
     */
    public function change_password()
    {
        return view('provider.profile.change_password');
    }

    /**
     * Change Password.
     *
     * @return \Illuminate\Http\Response
     */
    public function update_password(Request $request)
    {
        $this->validate($request, [
                'password' => 'required|min:6|confirmed',
                'old_password' => 'required',
            ]);

        $Provider = \Auth::user();

        if(password_verify($request->old_password, $Provider->password))
        {
            $Provider->password = bcrypt($request->password);
            $Provider->save();

            return back()->with('flash_success','Password changed successfully!');
        } else {
            return back()->with('flash_error','Please enter correct password');
        }
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function location_edit()
    {
        return view('provider.location.index');
    }

    /**
     * Update latitude and longitude of the user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function location_update(Request $request)
    {
        $this->validate($request, [
                'latitude' => 'required|numeric',
                'longitude' => 'required|numeric',
            ]);

        if($Provider = \Auth::user()){

            $Provider->latitude = $request->latitude;
            $Provider->longitude = $request->longitude;
            $Provider->save();

            return back()->with(['flash_success' => 'Location Updated successfully!']);

        } else {
            return back()->with(['flash_error' => 'Provider Not Found!']);
        }
    }

    /**
     * upcoming history.
     *
     * @return \Illuminate\Http\Response
     */
    public function upcoming_trips()
    {
        $fully = (new ProviderResources\TripController)->upcoming_trips();
        return view('provider.payment.upcoming',compact('fully'));
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */


    public function cancel(Request $request) {
        try{
            (new TripController)->cancel($request);
            return back();
        } catch (ModelNotFoundException $e) {
            return back()->with(['flash_error' => "Something Went Wrong"]);
        }
    }
}

resources/views/admin/providers/index.blade.php
@extends('admin.layout.base')

@section('title', 'Providers ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">
                @lang('admin.Providers')
                @if(Setting::get('demo_mode', 0) == 1)
                <span class="pull-right">(*personal information hidden in demo)</span>
                @endif
            </h5>
            <a href="{{ route('admin.provider.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> @lang('admin.Add New Provider') </a>
            <table class="table table-striped table-bordered dataTable" id="table-2">
                <thead>
                    <tr>
                        <th>@lang('admin.ID')</th>
                        <th>@lang('admin.Full_Name')</th>
                        <th>@lang('admin.Email')</th>
                        <th>@lang('admin.Mobile')</th>
                        <th>@lang('admin.Total_Requests')</th>
                        <th>@lang('admin.Accepted_Requests')</th>
                        <th>@lang('admin.Cancelled_Requests')</th>
                        <th>@lang('admin.Documents_Service_Type')</th>
                        <th>@lang('admin.Online')</th>
                        <th>@lang('admin.Action')</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($providers as $index => $provider)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $provider->first_name }} {{ $provider->last_name }}</td>
                        @if(Setting::get('demo_mode', 0) == 1)
                        <td>{{ substr($provider->email, 0, 3).'****'.substr($provider->email, strpos($provider->email, "@")) }}</td>
                        @else
                        <td>{{ $provider->email }}</td>
                        @endif
                        @if(Setting::get('demo_mode', 0) == 1)
                        <td>+919876543210</td>
                        @else
                        <td>{{ $provider->mobile }}</td>
                        @endif
                        <td>{{ $provider->total_requests }}</td>
                        <td>{{ $provider->accepted_requests }}</td>
                        <td>{{ $provider->total_requests - $provider->accepted_requests }}</td>
                        <td>
                            @if($provider->pending_documents() > 0 || $provider->service == null)
                                <a class="btn btn-danger btn-block label-right" href="{{route('admin.provider.index', $provider->id )}}">@lang('admin.Attention')<span class="btn-label">{{ $provider->pending_documents() }}</span></a>
                            @else
                                <a class="btn btn-success btn-block" href="{{route('admin.provider.index', $provider->id )}}">@lang('admin.All_Set')</a>
                            @endif
                        </td>
                        <td>
                            @if($provider->service)
                                @if($provider->service->status == 'active')
                                    <label class="btn btn-block btn-primary">@lang('admin.Yes')</label>
                                @else
                                    <label class="btn btn-block btn-warning">@lang('admin.No')</label>
                                @endif
                            @else
                                <label class="btn btn-block btn-danger">@lang('admin.N_A')</label>
                            @endif
                        </td>
                        <td>
                            <div class="input-group-btn">
                                @if($provider->status == 'approved')
                                <a class="btn btn-danger btn-block" href="{{ route('admin.provider.disapprove', $provider->id ) }}">@lang('admin.Disable')</a>
                                @else
                                <a class="btn btn-success btn-block" href="{{ route('admin.provider.approve', $provider->id ) }}">@lang('admin.Enable')</a>
                                @endif
                                <button type="button" 
                                    class="btn btn-info btn-block dropdown-toggle"
                                    data-toggle="dropdown">@lang('admin.Action')
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('admin.provider.request', $provider->id) }}" class="btn btn-default"><i class="fa fa-search"></i> @lang('admin.History')</a>
                                    </li>
                                    <li>
                                        <a href="{{ route('admin.provider.statement', $provider->id) }}" class="btn btn-default"><i class="fa fa-account"></i> @lang('admin.Statements')</a>
                                    </li>
                                    <li>
                                        <a href="{{ route('admin.provider.edit', $provider->id) }}" class="btn btn-default"><i class="fa fa-pencil"></i> @lang('admin.Edit')</a>
                                    </li>
                                    <li>
                                        <form action="{{ route('admin.provider.destroy', $provider->id) }}" method="POST">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button class="btn btn-default look-a-like" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i> @lang('admin.Delete')</button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                       <tr>
                        <th>@lang('admin.ID')</th>
                        <th>@lang('admin.Full_Name')</th>
                        <th>@lang('admin.Email')</th>
                        <th>@lang('admin.Mobile')</th>
                        <th>@lang('admin.Total_Requests')</th>
                        <th>@lang('admin.Accepted_Requests')</th>
                        <th>@lang('admin.Cancelled_Requests')</th>
                        <th>@lang('admin.Documents_Service_Type')</th>
                        <th>@lang('admin.Online')</th>
                        <th>@lang('admin.Action')</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/providers/statement.blade.php
@extends('admin.layout.base')

@section('title', $page)

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            <div class="box box-block bg-white">
            	<h3>{{$page}}</h3>

            	<div style="text-align: center;padding: 20px;color: blue;font-size: 24px;">
            		<p><strong>
            			<span>@lang('admin.Over_All_Earning'){{currency($revenue[0]->overall)}}</span>
            			<br>
            			<span>@lang('admin.Over_All_Commission'){{currency($revenue[0]->commission)}}</span>
            		</strong></p>
            	</div>

            	<div class="row">

	            	<div class="col-lg-4 col-md-6 col-xs-12">
						<div class="box box-block bg-white tile tile-1 mb-2">
							<div class="t-icon right"><span class="bg-danger"></span><i class="ti-rocket"></i></div>
							<div class="t-content">
								<h6 class="text-uppercase mb-1">@lang('admin.Total_No_of_Rides')</h6>
								<h1 class="mb-1">{{$rides->count()}}</h1>
								<span class="text-muted font-90">@lang('admin.down_from_cancelled_Request')</span>
							</div>
						</div>
					</div>


					<div class="col-lg-4 col-md-6 col-xs-12">
						<div class="box box-block bg-white tile tile-1 mb-2">
							<div class="t-icon right"><span class="bg-success"></span><i class="ti-bar-chart"></i></div>
							<div class="t-content">
								<h6 class="text-uppercase mb-1">@lang('admin.Revenue')</h6>
								<h1 class="mb-1">{{currency($revenue[0]->overall)}}</h1>
								<i class="fa fa-caret-up text-success mr-0-5"></i><span>@lang('admin.from') {{$rides->count()}} @lang('admin.Rides')</span>
							</div>
						</div>
					</div>

					<div class="col-lg-4 col-md-6 col-xs-12">
						<div class="box box-block bg-white tile tile-1 mb-2">
							<div class="t-icon right"><span class="bg-warning"></span><i class="ti-archive"></i></div>
							<div class="t-content">
								<h6 class="text-uppercase mb-1">@lang('admin.Cancelled_Rides')</h6>
								<h1 class="mb-1">{{$cancel_rides}}</h1>
								<i class="fa fa-caret-down text-danger mr-0-5"></i><span>@lang('admin.for') @if($cancel_rides == 0) 0.00 @else {{round($cancel_rides/$rides->count(),2)}}% @endif @lang('admin.Rides')</span>
							</div>
						</div>
					</div>

						<div class="row row-md mb-2" style="padding: 15px;">
							<div class="col-md-12">
									<div class="box bg-white">
										<div class="box-block clearfix">
											<h5 class="float-xs-left">@lang('admin.Earnings')</h5>
											<div class="float-xs-right">
											</div>
										</div>

										@if(count($rides) != 0)
								            <table class="table table-striped table-bordered dataTable" id="table-2">
								                <thead>
												<tr>
													<td>@lang('admin.Booking_ID')</td>
													<td>@lang('admin.Picked_up')</td>
													<td>@lang('admin.Dropped')</td>
													<td>@lang('admin.Request_Details')</td>
													<td>@lang('admin.Commission')</td>
													<td>@lang('admin.Dated_on')</td>
													<td>@lang('admin.Status')</td>
													<td>@lang('admin.Earned')</td>
												</tr>
								                
								                </thead>
								                <tbody>
								                <?php $diff = ['-success','-info','-warning','-danger']; ?>
														@foreach($rides as $index => $ride)
															<tr>
																<td>{{$ride->booking_id}}</td>
																<td>
																	@if($ride->s_address != '')
																		{{$ride->s_address}}
																	@else
																		Not Provided
																	@endif
																</td>
																<td>
																	@if($ride->d_address != '')
																		{{$ride->d_address}}
																	@else
																		Not Provided
																	@endif
																</td>
																<td>
																	@if($ride->status != "CANCELLED")
																		<a class="text-primary" href="{{route('admin.requests.show',$ride->id)}}"><span class="underline">@lang('admin.View_Ride_Details')</span></a>
																	@else
																		<span>@lang('admin.No_Details_Found') </span>
																	@endif									
																</td>
																<td>{{currency($ride->payment['commision'])}}</td>
																<td>
																	<span class="text-muted">{{date('d M Y',strtotime($ride->created_at))}}</span>
																</td>
																<td>
																	@if($ride->status == "COMPLETED")
																		<span class="tag tag-success">{{$ride->status}}</span>
																	@elseif($ride->status == "CANCELLED")
																		<span class="tag tag-danger">{{$ride->status}}</span>
																	@else
																		<span class="tag tag-info">{{$ride->status}}</span>
																	@endif
																</td>
																<td>{{currency($ride->payment['fixed'] + $ride->payment['distance'])}}</td>

															</tr>
														@endforeach
															
								                <tfoot>
								                   <tr>
														<td>@lang('admin.Booking_ID')</td>
														<td>@lang('admin.Picked_up')</td>
														<td>@lang('admin.Dropped')</td>
														<td>@lang('admin.Request_Details')</td>
														<td>@lang('admin.Commission')</td>
														<td>@lang('admin.Dated_on')</td>
														<td>@lang('admin.Status')</td>
														<td>@lang('admin.Earned')</td>
													</tr>
								                </tfoot>
								            </table>
								            @else
								            <h6 class="no-result">@lang('admin.No_results_found')</h6>
								            @endif 

									</div>
								</div>

							</div>

            	</div>
            </div>
        </div>
    </div>

@endsection